# Generated by Django 2.1.5 on 2021-07-30 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0005_remove_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
